alias: Knop C302 Bed 1
description: ""
triggers:
  - domain: mqtt
    device_id: 1788389a3b7df7b0d78b85bb4de7f5d9
    type: action
    subtype: single
    trigger: device
    id: single
  - domain: mqtt
    device_id: 1788389a3b7df7b0d78b85bb4de7f5d9
    type: action
    subtype: double
    trigger: device
    id: double
  - domain: mqtt
    device_id: 1788389a3b7df7b0d78b85bb4de7f5d9
    type: action
    subtype: long
    trigger: device
    id: long
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: single
          - condition: state
            entity_id: input_select.bed1_c302
            state: idle
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.bed1_c302
            data:
              option: call
          - action: rest_command.send_call_c302_1
      - conditions:
          - condition: trigger
            id: single
          - condition: not
            conditions:
              - condition: state
                entity_id: input_select.bed1_c302
                state: idle
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.bed1_c302
            data:
              option: idle
          - action: rest_command.send_idle_c302_1
      - conditions:
          - condition: trigger
            id: double
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.bed1_c302
            data:
              option: present
          - action: rest_command.send_present_c302_1
      - conditions:
          - condition: trigger
            id: long
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.bed1_c302
            data:
              option: extra
          - action: rest_command.send_extra_c302_1
mode: single